### ISSUE TITLE
some install problems

### ISSUE THREAD

**Issue by estolle** [MerrimanLab/selectionTools#17]
Hi there

I just tried to get the pipeline running and I had a few issues when installing it. I think I fixed most, but wanted to report it here in case others encounter them. If its not due to my specific system, maybe they can even be fixed permanently.
- I manually created $HOME/.local/bin   , however, it seems to be empty after the pipe installed.
- broken ShapeIt link: I updated install.sh with new link:
  http://mathgen.stats.ox.ac.uk/genetics_software/shapeit/old_versions/shapeit.v2.r790.Ubuntu_12.04.4.static.tar.gz
  --> FYI, there is also a newer version (http://mathgen.stats.ox.ac.uk/genetics_software/shapeit/shapeit.v2.r837.GLIBCv2.20.Linux.static.tgz)
- I got an error at the PyFasta installation:
  error: can't combine user with prefix, exec_prefix/home, or install_(plat)base
  manually typing python setup.py install --user reproduces it and looking up python setup.py install --help, it says for --user : "install in user site-package  '/home/estolle/.local/lib/python2.7/site-packages'  " --> does not exist, i guess therefore the error come up
  So I removed the --user flag in the install.sh  for pyfasta and pyvcf (eg here check_success python setup.py install --user). It now installed it into my Linuxbrew Python folders.

in the end the install log shows some more errors/warnings about standard_run_utilities.py:191: SyntaxWarning: name 'STOP' is used prior to global declaration. However, the pipe seems to be installing completely, so I am not sure if the warning is problematic.

Hope this helps =)

Cheers

Last parts of Install log FYI
Using /home/estolle/.linuxbrew/lib/python2.7/site-packages/setuptools-18.6.1-py2.7.egg
Finished processing dependencies for PyVCF==0.6.4
Installing selection_pipeline
/scratch/local/estolle/programs/selectionTools/selection_pipeline/standard_run_utilities.py:191: SyntaxWarning: name 'STOP' is used prior to global declaration
  global STOP
running install
running bdist_egg
running egg_info
creating selectionTools.egg-info
writing selectionTools.egg-info/PKG-INFO
writing top-level names to selectionTools.egg-info/top_level.txt
writing dependency_links to selectionTools.egg-info/dependency_links.txt
writing entry points to selectionTools.egg-info/entry_points.txt
writing manifest file 'selectionTools.egg-info/SOURCES.txt'
reading manifest file 'selectionTools.egg-info/SOURCES.txt'
writing manifest file 'selectionTools.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/selection_pipeline
copying selection_pipeline/_version.py -> build/lib/selection_pipeline
copying selection_pipeline/__init__.py -> build/lib/selection_pipeline
copying selection_pipeline/aa_annotate.py -> build/lib/selection_pipeline
copying selection_pipeline/haps_interpolate.py -> build/lib/selection_pipeline
copying selection_pipeline/multipipeline.py -> build/lib/selection_pipeline
copying selection_pipeline/standard_run.py -> build/lib/selection_pipeline
copying selection_pipeline/haps_to_hapmap.py -> build/lib/selection_pipeline
copying selection_pipeline/environment.py -> build/lib/selection_pipeline
copying selection_pipeline/haps_filters.py -> build/lib/selection_pipeline
copying selection_pipeline/standard_run_utilities.py -> build/lib/selection_pipeline
copying selection_pipeline/run_pipeline.py -> build/lib/selection_pipeline
copying selection_pipeline/selection_pipeline.py -> build/lib/selection_pipeline
creating build/lib/selection_pipeline/tests
copying selection_pipeline/tests/test_selection_pipeline.py -> build/lib/selection_pipeline/tests
copying selection_pipeline/tests/**init**.py -> build/lib/selection_pipeline/tests
copying selection_pipeline/tests/filter.haps -> build/lib/selection_pipeline/tests
copying selection_pipeline/tests/one_line.haps -> build/lib/selection_pipeline/tests
copying selection_pipeline/tests/triallelic_haps.haps -> build/lib/selection_pipeline/tests
copying selection_pipeline/tests/defaults.cfg -> build/lib/selection_pipeline/tests
copying selection_pipeline/tests/CEU_test.vcf -> build/lib/selection_pipeline/tests
copying selection_pipeline/tests/ancestor.fa -> build/lib/selection_pipeline/tests
copying selection_pipeline/tests/CEU_test.ids -> build/lib/selection_pipeline/tests
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/selection_pipeline
copying build/lib/selection_pipeline/_version.py -> build/bdist.linux-x86_64/egg/selection_pipeline
copying build/lib/selection_pipeline/__init__.py -> build/bdist.linux-x86_64/egg/selection_pipeline
copying build/lib/selection_pipeline/aa_annotate.py -> build/bdist.linux-x86_64/egg/selection_pipeline
copying build/lib/selection_pipeline/haps_interpolate.py -> build/bdist.linux-x86_64/egg/selection_pipeline
copying build/lib/selection_pipeline/multipipeline.py -> build/bdist.linux-x86_64/egg/selection_pipeline
copying build/lib/selection_pipeline/standard_run.py -> build/bdist.linux-x86_64/egg/selection_pipeline
copying build/lib/selection_pipeline/haps_to_hapmap.py -> build/bdist.linux-x86_64/egg/selection_pipeline
copying build/lib/selection_pipeline/environment.py -> build/bdist.linux-x86_64/egg/selection_pipeline
copying build/lib/selection_pipeline/haps_filters.py -> build/bdist.linux-x86_64/egg/selection_pipeline
copying build/lib/selection_pipeline/standard_run_utilities.py -> build/bdist.linux-x86_64/egg/selection_pipeline
copying build/lib/selection_pipeline/run_pipeline.py -> build/bdist.linux-x86_64/egg/selection_pipeline
creating build/bdist.linux-x86_64/egg/selection_pipeline/tests
copying build/lib/selection_pipeline/tests/ancestor.fa -> build/bdist.linux-x86_64/egg/selection_pipeline/tests
copying build/lib/selection_pipeline/tests/test_selection_pipeline.py -> build/bdist.linux-x86_64/egg/selection_pipeline/tests
copying build/lib/selection_pipeline/tests/CEU_test.vcf -> build/bdist.linux-x86_64/egg/selection_pipeline/tests
copying build/lib/selection_pipeline/tests/filter.haps -> build/bdist.linux-x86_64/egg/selection_pipeline/tests
copying build/lib/selection_pipeline/tests/**init**.py -> build/bdist.linux-x86_64/egg/selection_pipeline/tests
copying build/lib/selection_pipeline/tests/one_line.haps -> build/bdist.linux-x86_64/egg/selection_pipeline/tests
copying build/lib/selection_pipeline/tests/CEU_test.ids -> build/bdist.linux-x86_64/egg/selection_pipeline/tests
copying build/lib/selection_pipeline/tests/triallelic_haps.haps -> build/bdist.linux-x86_64/egg/selection_pipeline/tests
copying build/lib/selection_pipeline/tests/defaults.cfg -> build/bdist.linux-x86_64/egg/selection_pipeline/tests
copying build/lib/selection_pipeline/selection_pipeline.py -> build/bdist.linux-x86_64/egg/selection_pipeline
byte-compiling build/bdist.linux-x86_64/egg/selection_pipeline/_version.py to _version.pyc
byte-compiling build/bdist.linux-x86_64/egg/selection_pipeline/__init__.py to **init**.pyc
byte-compiling build/bdist.linux-x86_64/egg/selection_pipeline/aa_annotate.py to aa_annotate.pyc
byte-compiling build/bdist.linux-x86_64/egg/selection_pipeline/haps_interpolate.py to haps_interpolate.pyc
byte-compiling build/bdist.linux-x86_64/egg/selection_pipeline/multipipeline.py to multipipeline.pyc
byte-compiling build/bdist.linux-x86_64/egg/selection_pipeline/standard_run.py to standard_run.pyc
byte-compiling build/bdist.linux-x86_64/egg/selection_pipeline/haps_to_hapmap.py to haps_to_hapmap.pyc
byte-compiling build/bdist.linux-x86_64/egg/selection_pipeline/environment.py to environment.pyc
byte-compiling build/bdist.linux-x86_64/egg/selection_pipeline/haps_filters.py to haps_filters.pyc
byte-compiling build/bdist.linux-x86_64/egg/selection_pipeline/standard_run_utilities.py to standard_run_utilities.pyc
build/bdist.linux-x86_64/egg/selection_pipeline/standard_run_utilities.py:191: SyntaxWarning: name 'STOP' is used prior to global declaration
  global STOP
byte-compiling build/bdist.linux-x86_64/egg/selection_pipeline/run_pipeline.py to run_pipeline.pyc
byte-compiling build/bdist.linux-x86_64/egg/selection_pipeline/tests/test_selection_pipeline.py to test_selection_pipeline.pyc
byte-compiling build/bdist.linux-x86_64/egg/selection_pipeline/tests/**init**.py to **init**.pyc
byte-compiling build/bdist.linux-x86_64/egg/selection_pipeline/selection_pipeline.py to selection_pipeline.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying selectionTools.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying selectionTools.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying selectionTools.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying selectionTools.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying selectionTools.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying selectionTools.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating dist
creating 'dist/selectionTools-1.1.1-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing selectionTools-1.1.1-py2.7.egg
creating /home/estolle/.linuxbrew/lib/python2.7/site-packages/selectionTools-1.1.1-py2.7.egg
Extracting selectionTools-1.1.1-py2.7.egg to /home/estolle/.linuxbrew/lib/python2.7/site-packages
/home/estolle/.linuxbrew/lib/python2.7/site-packages/selectionTools-1.1.1-py2.7.egg/selection_pipeline/standard_run_utilities.py:191: SyntaxWarning: name 'STOP' is used prior to global declaration
  global STOP
Adding selectionTools 1.1.1 to easy-install.pth file
Installing selection_pipeline script to /home/estolle/.linuxbrew/bin
Installing ancestral_annotation script to /home/estolle/.linuxbrew/bin
Installing haps_to_hapmap script to /home/estolle/.linuxbrew/bin
Installing haps_filters script to /home/estolle/.linuxbrew/bin
Installing multipop_selection_pipeline script to /home/estolle/.linuxbrew/bin
Installing haps_interpolate script to /home/estolle/.linuxbrew/bin

Installed /home/estolle/.linuxbrew/lib/python2.7/site-packages/selectionTools-1.1.1-py2.7.egg
Processing dependencies for selectionTools==1.1.1
Finished processing dependencies for selectionTools==1.1.1

**Comment by smilefreak** [comment]
Thanks for this, adding this new link to the readme.

I think @murraycadzow is going to be doing some updates and will update the pipeline then.
