### ISSUE TITLE
install.sh does not put anything in $HOME/.local/bin

### ISSUE THREAD

**Issue by b-wharam** [MerrimanLab/selectionTools#8]
Hi,
I am excited at the prospect of this pipeline as described in your paper. I am running a 64 bit Ubuntu 12.04 LTS, though I am quite inexperienced as a linux user.
I downloaded, extracted and ran the ./install.sh

selection_pipeline -h shows command not found

The directory $HOME/.local/bin did not exist, but $HOME/.local/share did. I tried creating $HOME/.local/bin and then rerunning ./install.sh, but .local/bin remains empty

As you mention in the documentation $HOME/.local/bin needs to be added to $PATH. I have done this and checked by typing $PATH. 
1. Can you think of what might be going wrong?
2. Alternatively, can I change install.sh so that it installs the executables in a different directory, and I can add that to $PATH instead?

**Comment by murraycadzow** [comment]
Hi,
Great to hear of your interest.
Could you run "./install.sh >> install.log 2>> install.log" inside the selectionTools directory and paste the contents of install.log please. That will let me know what is succeeding and what is failing during the install

thanks
Murray

**Comment by smilefreak** [comment]
Also, in addition to the installation log murray asked for,  can you paste the output of the following commands.
```
    echo $PATH
    ls $HOME/.local/bin
```

**Comment by b-wharam** [comment]
Hey guys, thanks for quick response.

bw9652@it021300:~/selectionTools-master$ echo $PATH
/usr/bin:/bin:/usr/local/bin:/usr/local/sbin:/bin:/home/bw9652/.local/bin:/usr/local/bin
bw9652@it021300:~/selectionTools-master$  ls $HOME/.local/bin

nothing comes up - .local/bin is empty

bw9652@it021300:~/.local$ ls
bin  share

but .local/bin does exist

---------------------------------------------
Attached is install.log

What is immediately apparent is
Installing PyFasta
python: can't open file 'setup.py': [Errno 2] No such file or directory
error with python

I am running
Python 2.7.3 (default, Dec 18 2014, 19:10:20)
[GCC 4.6.3] on linux2

setuptools numpy and scipy are all upto date.

Best wishes
Barney

On 17 February 2015 at 03:26, James Boocock <notifications@github.com>
wrote:

> Also, in addition to the installation log murray asked for, can you paste
> the output of the following commands.
>
>     echo $PATH
>     ls $HOME/.local/bin
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/smilefreak/selectionTools/issues/8#issuecomment-74612029>
> .
>



-- 
Barney Wharam
(PhD Student)
Nematode Biology (Lab: 245, 246; Office 2A09)
Life Sciences Building
The University of Bristol,

**Comment by b-wharam** [comment]
Hi

It occured to me this might help you help me:
bw9652@it021300:~/selectionTools-master$ ls -l
total 76
drwxrwxr-x 2 bw9652 bw9652 4096 Feb 17 15:51 bin
drwxrwxr-x 2 bw9652 bw9652 4096 Oct 31 11:14 corescripts
-rw-rw-r-- 1 bw9652 bw9652 2800 Feb 17 15:52 defaults.cfg
drwxrwxr-x 3 bw9652 bw9652 4096 Oct 31 11:14 docs
drwxrwxr-x 2 bw9652 bw9652 4096 Oct 31 11:14 extrascripts
drwxrwxr-x 2 bw9652 bw9652 4096 Oct 31 11:14 galaxy
drwxrwxr-x 2 bw9652 bw9652 4096 Feb 17 15:50 include
-rwxr-xr-x 1 bw9652 bw9652 4157 Oct 31 11:14 install.sh
drwxrwxr-x 4 bw9652 bw9652 4096 Feb 17 15:50 lib
-rw-rw-r-- 1 bw9652 bw9652 1098 Oct 31 11:14 LICENSE
drwxrwxr-x 2 bw9652 bw9652 4096 Oct 31 11:14 pyfasta
drwxrwxr-x 2 bw9652 bw9652 4096 Oct 31 11:14 PyVCF
-rw-rw-r-- 1 bw9652 bw9652 2682 Oct 31 11:14 README.md
drwxrwxr-x 6 bw9652 bw9652 4096 Oct 31 11:14 referencefiles
drwxrwxr-x 3 bw9652 bw9652 4096 Oct 31 11:14 selection_pipeline
-rw-rw-r-- 1 bw9652 bw9652 1179 Oct 31 11:14 setup.py
drwxrwxr-x 3 bw9652 bw9652 4096 Feb 17 15:50 share
drwxrwxr-x 2 bw9652 bw9652 4096 Oct 31 11:14 src

Do i need to run some kind of chmod on my setup.py? / do you need to
include that in the install.sh?

Best wishes
Barney



On 17 February 2015 at 15:03, Barney Wharam <Barney.Wharam@bristol.ac.uk>
wrote:

> Hey guys, thanks for quick response.
>
> bw9652@it021300:~/selectionTools-master$ echo $PATH
>
> /usr/bin:/bin:/usr/local/bin:/usr/local/sbin:/bin:/home/bw9652/.local/bin:/usr/local/bin
> bw9652@it021300:~/selectionTools-master$  ls $HOME/.local/bin
>
> nothing comes up - .local/bin is empty
>
> bw9652@it021300:~/.local$ ls
> bin  share
>
> but .local/bin does exist
>
> ---------------------------------------------
> Attached is install.log
>
> What is immediately apparent is
> Installing PyFasta
> python: can't open file 'setup.py': [Errno 2] No such file or directory
> error with python
>
> I am running
> Python 2.7.3 (default, Dec 18 2014, 19:10:20)
> [GCC 4.6.3] on linux2
>
> setuptools numpy and scipy are all upto date.
>
> Best wishes
> Barney
>
> On 17 February 2015 at 03:26, James Boocock <notifications@github.com>
> wrote:
>
>> Also, in addition to the installation log murray asked for, can you paste
>> the output of the following commands.
>>
>>     echo $PATH
>>     ls $HOME/.local/bin
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/smilefreak/selectionTools/issues/8#issuecomment-74612029>
>> .
>>
>
>
>
> --
> Barney Wharam
> (PhD Student)
> Nematode Biology (Lab: 245, 246; Office 2A09)
> Life Sciences Building
> The University of Bristol,
>
>
>


-- 
Barney Wharam
(PhD Student)
Nematode Biology (Lab: 245, 246; Office 2A09)
Life Sciences Building
The University of Bristol,

**Comment by dalloliogm** [comment]
Hi,
I also tried to install selectionTools on my computer (a Mac), but it didn't install the executables in a PATH folder. See the install log here: http://pastebin.com/bJYpRq6R 
Note that a previous version of selectionTools was installed on this system.

The binary was installed in ~/Library/Python/2.7/bin/selection_pipeline 

```
$: echo PATH
/Library/Frameworks/Python.framework/Versions/3.4/bin:/opt/local/bin:/opt/local/sbin:/Users/gioby/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/texbin

$: echo $PYTHONPATH
://Users/gioby/usr/lib/
```

**Comment by murraycadzow** [comment]
Hi Barney and Dio

Barney:
could you paste the contents of you install.log file into a pastebin or simliar and post the link here, your log didn't attach.

Dio:
Could you do a "ls" on the selectionTools/bin directory and see if shapeit exists, if it doesn't you can manually download it here https://mathgen.stats.ox.ac.uk/genetics_software/shapeit/shapeit.html#download and extract the binary into selectionTools/bin
could you also "ls ~/Library/Python/2.7/bin/selection_pipeline" and paste the contents

thanks
Murray

**Comment by b-wharam** [comment]
Here is my install.log

http://pastebin.com/BSeDJ4hS


On 18 February 2015 at 20:21, murraycadzow <notifications@github.com> wrote:

> Hi Barney and Dio
>
> Barney:
> could you paste the contents of you install.log file into a pastebin or
> simliar and post the link here, your log didn't attach.
>
> Dio:
> Could you do a "ls" on the selectionTools/bin directory and see if shapeit
> exists, if it doesn't you can manually download it here
> https://mathgen.stats.ox.ac.uk/genetics_software/shapeit/shapeit.html#download
> and extract the binary into selectionTools/bin
> could you also "ls ~/Library/Python/2.7/bin/selection_pipeline" and paste
> the contents
>
> thanks
> Murray
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/smilefreak/selectionTools/issues/8#issuecomment-74940253>
> .
>



-- 
Barney Wharam
(PhD Student)
Nematode Biology (Lab: 245, 246; Office 2A09)
Life Sciences Building
The University of Bristol,

**Comment by murraycadzow** [comment]
Thanks Barney,

We think your issue may be with your python setuptools being too old.

If you are able this command should sort out the python issues for you (python setuptools is what originally creates $HOME/.local/bin). I have added scipy and numpy in the command just in case you don't have them installed already

sudo apt-get install python-setuptools python-scipy python-numpy

then you can run the install.sh again

Murray

**Comment by b-wharam** [comment]
Hey guys,

I ran command as you said, all was already upto date
Reading package lists... Done
Building dependency tree
Reading state information... Done
python-numpy is already the newest version.
python-setuptools is already the newest version.
python-scipy is already the newest version.
0 to upgrade, 0 to newly install, 0 to remove and 10 not to upgrade.
bw9652@it021300:~$ ^C

Do you have any other ideas?
Best wishes
Barney



On 19 February 2015 at 20:37, murraycadzow <notifications@github.com> wrote:

> Thanks Barney,
>
> We think your issue may be with your python setuptools being too old.
>
> If you are able this command should sort out the python issues for you
> (python setuptools is what originally creates $HOME/.local/bin). I have
> added scipy and numpy in the command just in case you don't have them
> installed already
>
> sudo apt-get install python-setuptools python-scipy python-numpy
>
> then you can run the install.sh again
>
> Murray
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/smilefreak/selectionTools/issues/8#issuecomment-75131021>
> .
>



-- 
Barney Wharam
(PhD Student)
Nematode Biology (Lab: 245, 246; Office 2A09)
Life Sciences Building
The University of Bristol,

**Comment by murraycadzow** [comment]
Hi Barney,

I haven't thought of what is causing your issue but I did manage to install without too much issue on a vm

maybe that would be an option for you

Murray

**Comment by cae803** [comment]
Hi.
I am very glad to meet the pipeline. However, I have problems like this issue. Could you tell me how to change my install process? My environments are the following.

OS: OS X Yosemite 10.10.2
Python: 2.7.9
Install log:  http://pastebin.com/WK0MhjEB

$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/Kae1/.local/bin:/usr/local/share/python

$ ls $HOME/.local/bin
(nothing)

$ ls ~/program/selectionTools/bin
beagle.jar		vcf-annotate		vcf-query
bgzip			vcf-compare		vcf-shuffle-cols
fill-aa			vcf-concat		vcf-sort
fill-an-ac		vcf-consensus		vcf-stats
fill-fs			vcf-contrast		vcf-subset
fill-ref-md5		vcf-convert		vcf-to-tab
impute2			vcf-fix-ploidy		vcf-tstv
plink			vcf-indel-stats		vcf-validator
qctool			vcf-isec		vcftools
shapeit			vcf-merge
tabix			vcf-phased-join


$ ls ~/Library/Python/2.7/bin
ancestral_annotation		multipop_selection_pipeline
easy_install			pyfasta
easy_install-2.7		selection_pipeline
haps_filters			vcf_filter.py
haps_interpolate		vcf_melt
haps_to_hapmap


$ pip install --upgrade setuptools
Requirement already up-to-date: setuptools in /usr/local/lib/python2.7/site-packages/setuptools-15.0-py2.7.egg

$ pip install --upgrade numpy
Requirement already up-to-date: numpy in /usr/local/lib/python2.7/site-packages

$ pip install --upgrade scipy
Requirement already up-to-date: scipy in /usr/local/lib/python2.7/site-packages


Sincerely,
Kae

**Comment by smilefreak** [comment]
Hi Kaye, 

I think because you are running in a mac OSX environment it gets added
to this folder.
 /Users/Kae1/Library/Python/2.7/bin

You may have to add this folder to your path.

**Comment by cae803** [comment]
Thanks James,

I could run a command "selection_pipeline -h", because I added that path. I appreciate your support and help so much!

Best wishes,
Kae
